# trim FASTQ files generated by UCSF CRISPR library

# Example read:
# @SNL170:276:C8C5YACXX:8:2209:1290:2032 1:N:0:CTTGTA
# NGGACTGCGCGTCTCTGGAGTTTAAGAGCTTGGGGCCTAAGGGCAGCATC
# +
# #1=DDFFFHHHHHIIIIIIH:CG@F?:?BBD1?BGD00.88=C5-5-..=

#             NGGACTGCGCGTCTCTGGAGTTTAAGAGCTTGGGGCCTAAGGGCAGCATC # READ
# CCACCTTGTTGGTGGACTGCGCGTCTCTGGAGTTTAAGAGCTAAGCTG               # oligo sequence


from optparse import OptionParser

parser = OptionParser()
parser.add_option("-i", "--file_in", dest="fn_in", help="path to fastq", default="")
parser.add_option("-o", "--file_out", dest="fn_out", help="path to new fastq", default="")
(options, args) = parser.parse_args()
fn_in = options.fn_in
fn_out = options.fn_out
f = open(fn_in)
if fn_in==fn_out: 
    raise RuntimeException("fn_in and fn_out cannot be the same")
fo = open(fn_out, "w")
ctr=1
for line in f:
    if ctr==1:
        fo.write(line)
    elif ctr==2:
        fo.write( line[1:25] + '\n')
    elif ctr==3:
        fo.write(line)
    elif ctr==4:
        fo.write(line[1:25] + '\n')
    ctr = ctr+1
    if ctr==5:
        ctr=1

fo.close()
f.close()
    

